### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by opennota** [nokka/d2s#2]
The following program crashes with "index out of range":

``` go
package main

import (
	"strings"

	"github.com/nokka/d2s"
)

var data = "00000000000000000000" +
	"00000000000000000000" +
	"\x000000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"00000000000000000000" +
	"0000000\r0000\x1c000x000" +
	"\xe2?if0000000000000000" +
	"00000000000000JM00JM" +
	"00000\xda"

func main() {
	d2s.Parse(strings.NewReader(data))
}
```

(found with [go-fuzz](https://github.com/dvyukov/go-fuzz))

**Comment by nokka** [comment]
Hey! yeah I think it's because a diablo 2 binary file is at least 767 bytes of data. The header, so this string might be too short, and crash the header parser here: https://github.com/nokka/d2s/blob/master/d2s.go#L67.

I'll have a look!

**Comment by opennota** [comment]
`io.ReadFull` wouldn't panic if there were less than 767 bytes. And the above program panics here:

https://github.com/nokka/d2s/blob/c8f86bcc2b41cdc008346b94ef6f0f1e0f15c570/d2s.go#L628

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/nokka/d2s.parseItemList(0x5aa120, 0xc42005a6c0, 0x3030, 0x5dbbc0, 0x4e0880, 0xc420015774, 0x0, 0x0)
        /home/opennota/gocode/src/github.com/nokka/d2s/d2s.go:628 +0x16a3
github.com/nokka/d2s.parseItems(0x5aa120, 0xc42005a6c0, 0xc420010800, 0x0, 0x0)
        /home/opennota/gocode/src/github.com/nokka/d2s/d2s.go:222 +0x233
github.com/nokka/d2s.Parse(0x5aa3e0, 0xc42000a260, 0x1, 0x0, 0x0)
        /home/opennota/gocode/src/github.com/nokka/d2s/d2s.go:34 +0x149
main.main()
        /home/opennota/d2s.go:53 +0x8e
```
